### ISSUE TITLE
心电绘制

### ISSUE THREAD

**Issue by tianliangle3528** [debuggerx01/ecg_viewer_dart#1]
您好，我现在需要做一个fluter的app，里面需要一个心电动态折线绘制，看您是有相关的经验，可以请教一下您吗

**Comment by debuggerx01** [comment]
有什么问题？
我是使用的 fl_chart 这个库做的心电图实时显示，报表页面需要交互时则是利用webview加载echarts实现的，供参考。

[https://apps.apple.com/cn/app/%E7%99%BE%E4%BA%8C%E5%81%A5%E5%BA%B7/id1561137754](https://apps.apple.com/cn/app/%E7%99%BE%E4%BA%8C%E5%81%A5%E5%BA%B7/id1561137754)
